export const iso2ToIso3: { [key: string]: string } = {
  AE: "ARE",
  AR: "ARG",
  AT: "AUT",
  AU: "AUS",
  BA: "BIH",
  BE: "BEL",
  BG: "BGR",
  CA: "CAN",
  CH: "CHE",
  CO: "COL",
  CZ: "CZE",
  DE: "DEU",
  DK: "DNK",
  ES: "ESP",
  FI: "FIN",
  FR: "FRA",
  GB: "GBR",
  GR: "GRC",
  HR: "HRV",
  HU: "HUN",
  IE: "IRL",
  IL: "ISR",
  IN: "IND",
  IT: "ITA",
  JP: "JPN",
  KR: "KOR",
  LT: "LTU",
  LU: "LUX",
  MX: "MEX",
  MY: "MYS",
  NL: "NLD",
  NO: "NOR",
  NZ: "NZL",
  PL: "POL",
  PT: "PRT",
  RO: "ROU",
  RS: "SRB",
  RU: "RUS",
  SE: "SWE",
  SG: "SGP",
  SI: "SVN",
  SK: "SVK",
  TR: "TUR",
  UA: "UKR",
  US: "USA",
  VI: "VIR",
  ZA: "ZAF",
  BR: "BRA",
  CN: "CHN",
  TH: "THA",
  TW: "TWN",
  VN: "VNM",
  ID: "IDN",
  PH: "PHL",
  SA: "SAU",
  EG: "EGY",
  NG: "NGA",
  KE: "KEN",
  MA: "MAR",
  TN: "TUN",
};

export const regionCountries: Record<string, string[]> = {
  'Europe': ['FRA', 'DEU', 'GBR', 'ITA', 'ESP', 'POL', 'ROU', 'NLD', 'BEL', 'GRC', 'CZE', 'PRT', 'HUN', 'SWE', 'AUT', 'BGR', 'DNK', 'FIN', 'SVK', 'IRL', 'HRV', 'LTU', 'SVN', 'LVA', 'EST', 'CYP', 'LUX', 'MLT', 'NOR', 'CHE', 'ISL', 'ALB', 'MKD', 'SRB', 'BIH', 'MNE', 'UKR', 'BLR', 'MDA'],
  'North America': ['USA', 'CAN', 'MEX', 'GTM', 'CUB', 'HTI', 'DOM', 'HND', 'NIC', 'SLV', 'CRI', 'PAN', 'JAM', 'TTO', 'BHS', 'BRB'],
  'South America': ['BRA', 'ARG', 'COL', 'PER', 'VEN', 'CHL', 'ECU', 'BOL', 'PRY', 'URY', 'GUY', 'SUR'],
  'Africa': ['NGA', 'ETH', 'EGY', 'COD', 'TZA', 'ZAF', 'KEN', 'UGA', 'DZA', 'SDN', 'MAR', 'AGO', 'GHA', 'MOZ', 'MDG', 'CMR', 'CIV', 'NER', 'BFA', 'MLI', 'MWI', 'ZMB', 'SOM', 'SEN', 'TCD', 'ZWE', 'GIN', 'RWA', 'BEN', 'TUN', 'BDI', 'SSD', 'TGO', 'SLE', 'LBY', 'LBR', 'MRT', 'CAF', 'ERI', 'GMB', 'BWA', 'NAM', 'GAB', 'LSO', 'GNB', 'GNQ', 'MUS', 'SWZ', 'DJI', 'COM', 'CPV', 'STP', 'SYC'],
  'Oceania': ['AUS', 'PNG', 'NZL', 'FJI', 'SLB', 'NCL', 'PYF', 'VUT', 'WSM', 'KIR', 'TON', 'FSM', 'PLW', 'MHL', 'TUV', 'NRU'],
  'South Asia': ['IND', 'PAK', 'BGD', 'AFG', 'NPL', 'LKA', 'BTN', 'MDV'],
  'East Asia': ['CHN', 'JPN', 'KOR', 'TWN', 'MNG', 'PRK', 'HKG', 'MAC', 'VNM', 'THA', 'MMR', 'KHM', 'LAO', 'MYS', 'SGP', 'IDN', 'PHL', 'BRN', 'TLS']
};

export const regions = [
  { label: 'World', coords: [20, 0, 2] as [number, number, number] },
  { label: 'Europe', coords: [48, 12.5, 4.3] as [number, number, number] },
  { label: 'North America', coords: [48, -100, 3.2] as [number, number, number] },
  { label: 'South America', coords: [-25, -60, 3.2] as [number, number, number] },
  { label: 'Africa', coords: [0, 22, 3.3] as [number, number, number] },
  { label: 'Oceania', coords: [-20, 135, 3.5] as [number, number, number] },
  { label: 'South Asia', coords: [28, 78, 4] as [number, number, number] },
  { label: 'East Asia', coords: [58, 105, 3.5] as [number, number, number] }
];
